FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir \
    streamlit \
    langchain \
    langchain-core \
    langchain-community \
    langchain-ollama \
    scikit-learn \
    numpy==1.26.4 \
    torch \
    faiss-cpu \
    sentence-transformers \
    pandas

COPY src/ ./src/
COPY models/ ./models/
COPY data/ ./data/
COPY assets/ ./assets/

EXPOSE 8501

CMD ["streamlit", "run", "src/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
